recipient = input ("Enter the recipient:")
message = input ("Enter the message:")
name = input ("Enter the name:")
subject = input ("Enter the subject:")
version = float (input ("Enter the version:"))
discount = float (input("Enter the discount:"))
status = input ("Enter the status:")
code = input ("Enter the code:")
location = input ("Enter the location:")
age = input ("Enter the age:")
company = input ("Enter the company name:")
website = input ("Enter the website:")
phone = input ("Enter the phone:")
job_title = input ("Enter the job title:")
department = input ("Enter the department:")


print(f"\nDear {recipient}, I hope this email finds you well.\n")
print(message)
print(f"\nSubject: {subject}")
print(f"Sender: {name}")
print(f"Version: {version}")
print(f"Discount: {discount:.2f}%")
print(f"Status:{status}")
print(f"Code:{code}")
print(f"Location:{location}")
print(f"Age:{age}")
print(f"Company:{company}")
print(f"Website:{website}")
print(f"Phone:{phone}")
print(f"Job Title:{job_title}")
print(f"Department:{department}")
