print("Activity #3")
print("Dane Ralph U. Nacario")
print("February 6, 2025\n")

print("Character A:\t \"Hello there!\"")
print("Character B:\t \'Hi! How are you?\'")
print("Character A:\t \'I'm doing great.\' Thanks for asking!")
print("Character C:\t \"Hey, what's going on?\"")
print("Character B:\t \"We were just catching up.\"")
print("Character A:\t \"Yeah, it's been a while.\"")
print("Character C:\t \"Nice to see you both!\"")
print("Character B:\t \"Likewise! How have you been?\"")
print("Character C:\t \"I've been good. Thanks!\"")
print("Character A:\t \"That's great to hear.\"")
